// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfKUIoVYUExxA-rDEVJt8X3ieLsrfd7QI',
    appId: '1:423590894914:web:411f4f664fccac13887cdb',
    messagingSenderId: '423590894914',
    projectId: 'mymoney-15424',
    authDomain: 'mymoney-15424.firebaseapp.com',
    storageBucket: 'mymoney-15424.appspot.com',
    measurementId: 'G-209PPX5WQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABDn-JDracnP2iaS9az-wbEY6WL9kCi20',
    appId: '1:423590894914:android:4c17f454c34db509887cdb',
    messagingSenderId: '423590894914',
    projectId: 'mymoney-15424',
    storageBucket: 'mymoney-15424.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg_RpysLtatw3ri2uqmyHsTgOcVJQyZ6U',
    appId: '1:423590894914:ios:c4faa618b40ac5f4887cdb',
    messagingSenderId: '423590894914',
    projectId: 'mymoney-15424',
    storageBucket: 'mymoney-15424.appspot.com',
    iosBundleId: 'com.example.mymoney',
  );
}
